---
- name: debian | updating apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
  when: ansible_distribution == "Debian"

- name: debian | adding docker apt-key
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
  with_items: docker_ubuntu_repo_info

- name: debian | adding docker repo
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: docker_ubuntu_repo_info

- name: debian | uninstalling old docker package (if exists)
  apt:
    name: lxc-docker
    state: absent
    purge: yes

- name: debian | installing docker pre-reqs
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: debian | installing docker
  apt:
    name: docker-engine
    state: present

- name: debian | setting grub memory limit (if set)
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'
  register: grub_updated
  when: >
        docker_set_grub_memory_limit is defined and
        docker_set_grub_memory_limit

- name: debian | updating grub (if updated)
  command: update-grub
  when: grub_updated.changed

- name: debian | installing additonal packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bridge-utils
